---
title: "Final Projects"
output: html_document
---

At the end of the semester, a final project will be completed by each students. This project aims to combine all the different statistical techniques and R code learnt to analyse real datasets. This project is an individual projects that will evaluate the skills in statistics of students. 
Each student will choose a dataset of their choice or from one given in class. Students should conduct analysis in R and write a report and perform a presentation of their findings. 

## Reports of the final projects

The report should include:

1. **A background including:**
** A question student is seeking to answer.
** The real-world significance of this question; should include
        an explanation as to why this is an important question to
        investigate. This should require some background
        information (e.g., the state of North Carolina is
        investing heavily in developing shellfish aquaculture
        infrastructure, so interest in shellfish harvest trends
        is high).
o Data used in the analysis; should describe the source of the data, measurements, resolution, and any additional information needed to understand the scope and limitations of the data.


2. **A complete analysis of the dataset chosen:**
o Exploratory data analysis – include summary statistics
        and visualizations that reveal trends in the data.
        Summary statistics should be presented in a table. At a
        minimum, 3 visualizations should be included. These
        visualizations should be distinct in plot type and
        satisfy the “principles of data visualization.”
o Hypothesis testing – include a minimum of one hypothesis test (note: hypothesis testing associated with linear regression does not count). Explain the scientific and statistical hypotheses, and the tests chosen for this analysis. Provide full interpretation of the results. An example scientific hypothesis might be, shellfish harvests dropped after the year 2000.
o Linear regression – include a minimum of one linear regression model. Explain why you chose the explanatory variable(s) you did. Include diagnostic plots, significance of intercept and coefficient, and a visualization of the modeled and observed data (modeled and observed plotted in the same figure). Provide full interpretation of the results.

3. **Conclusions**
o Explain your main findings
o Loop back to your original question – did your analysis
answer your question?
o Describe what other data are needed to perform a more
        thorough, robust, and in-depth analysis than the one you
presented here
o What were the drawbacks of the approaches you used in
this project?
o Loop back to the motivation for this project – how do
        your results relate to the real-world significance that
        you outlined?
        
4. **Formatting**
o The report should be written as a professional engineering document. The same formatting guidelines that applied to your lab reports will also apply here (e.g., do not use personal pronouns, write appropriate figure captions, etc.).
   
o R code should be nicely formatted such that Dr. Nelson and Lise can easily follow your steps.


## Presentation of the final projects

Summarize the background, analysis, and conclusions of your
project. Presentation should be a maximum of 10 slides,
including the title slide. Presentation will be graded with the
following criteria:
o Slides are nicely-organized
o Presenter describes the background and analyses such that the
audience understands the overall flow of the project
o Presenter provides main findings from the analysis
o Presenter demonstrates understanding of the work performed